# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kelly Hubble
tagline:          It's subtle
url:              http://kellyhubble.com/
paginate:         1
baseurl:          /
pages_list:       
  About: '/about/'
  Feed: '/atom.xml/'

author:
  name:           Kelly Hubble
  url:            kellyhubble.com
  email:          kelly.hubble@gmail.com

# Custom vars
version:          0.0.1
#github:
#  repo:           https://github.com/poole/poole
